### ISSUE TITLE
Issue during evaluation with 1-3_train.ipynb.

### ISSUE THREAD

**Issue by ninfueng** [pometa0507/6th-ai-reference2#1]
Hello there,

Thank you very much for creating this tutorial.

I have a problem while running the evaluation in `1-3_train.ipynb`.
I got an error below:

```python
#################################
# EVAL
#################################
Generate output labels...
[100.0%][===================>][9.44it/s][00:07>00:00]   
generate label finished(25.19/s). start eval:
Traceback (most recent call last):                                              
  File "/work/second.pytorch/second/data/nusc_eval.py", line 18, in <module>
    fire.Fire(eval_main)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/work/second.pytorch/second/data/nusc_eval.py", line 12, in eval_main
    nusc_eval = NuScenesEval(nusc, config=cfg, result_path=res_path, eval_set=eval_set, 
  File "/usr/local/lib/python3.8/dist-packages/nuscenes/eval/detection/evaluate.py", line 82, in __init__
    self.gt_boxes = load_gt(self.nusc, self.eval_set, DetectionBox, verbose=verbose)
  File "/usr/local/lib/python3.8/dist-packages/nuscenes/eval/common/loaders.py", line 129, in load_gt
    raise Exception('Error: GT annotations must not have more than one attribute!')
Exception: Error: GT annotations must not have more than one attribute!
[
  {
    "token": "2b41120736de26519c22cea7c9874133"
  }
]
Command 'python "/work/second.pytorch/second/data/nusc_eval.py" --root_path="../data/3d_labels_painted" --version=v1.0-trainval --eval_version=detection_cvpr_2019 --res_path="/work/second.pytorch/checkpoints/model/results/step_4000/results_nusc.json" --eval_set=val --output_dir="/work/second.pytorch/checkpoints/model/results/step_4000"' returned non-zero exit status 1.
[
  {
    "token": "2b41120736de26519c22cea7c9874133"
  }
]
Traceback (most recent call last):
  File "../second.pytorch/second/pytorch/train.py", line 667, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "../second.pytorch/second/pytorch/train.py", line 430, in train
    raise e
  File "../second.pytorch/second/pytorch/train.py", line 410, in train
    result_dict = eval_dataset.dataset.evaluation(
  File "/work/second.pytorch/second/data/nuscenes_dataset.py", line 445, in evaluation
    res_nusc = self.evaluation_nusc(detections, output_dir)
  File "/work/second.pytorch/second/data/nuscenes_dataset.py", line 408, in evaluation_nusc
    subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python "/work/second.pytorch/second/data/nusc_eval.py" --root_path="../data/3d_labels_painted" --version=v1.0-trainval --eval_version=detection_cvpr_2019 --res_path="/work/second.pytorch/checkpoints/model/results/step_4000/results_nusc.json" --eval_set=val --output_dir="/work/second.pytorch/checkpoints/model/results/step_4000"' returned non-zero exit status 1.
```

I run this evaluation with your docker. This seems still have this problem.
Do you have any suggestions on how to fix this?

**Comment by pometa0507** [comment]
Hi, please try this step.
https://github.com/pometa0507/6th-ai-reference2#%E3%83%87%E3%83%BC%E3%82%BF%E3%82%BB%E3%83%83%E3%83%88%E3%81%AE%E7%94%A8%E6%84%8F

> 評価(Evaluation)を実行するために、修正版のsample_annotation.jsonを[Google Drive](https://drive.google.com/file/d/1KA_iF4X3DD3khr4_bdG4nG-KdWAkWB_9/view?usp=sharing)よりダウンロードして、既存の3d_labels/v1.0-trainval/sample_annotation.jsonに上書き保存してください。

In English.
> Please download the modified version of sample_annotation.json from [Google Drive](https://drive.google.com/file/d/1KA_iF4X3DD3khr4_bdG4nG-KdWAkWB_9/view?usp=sharing)
> and  Overwrite existing 3d_labels/v1.0-trainval/sample_annotation.json.

**Comment by ninfueng** [comment]
Thank you.

It works now. Can you tell me what was modified in `sample_annotation.json`?

**Comment by pometa0507** [comment]
In this competition, attributes are not used for either training or inference.
However, if there is more than one attribute, an error will occur during evaluation, so i have modified it so that there is only one attribute. (Remove duplicate attributes)
